import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.metrics.pairwise import cosine_similarity
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import leidenalg
import igraph as ig

def extract_words(filepath: str, coverage_ratio: float) -> list[tuple[str, float]]:
    """
    Extracts the most important keywords from the cleaned text in the CSVs 
    
    Arguments:
        filepath: the path to the CSV file containing the cleaned text
        coverage_ratio: The ratio of total TF-IDF score coverage to determine how many top keywords to keep (default: 0.5 for 50% coverage), provides adaptability to different datasets.
    Returns:
        A list of tuples containing the most important keywords and their scores
    """
    df = pd.read_csv(filepath, usecols=['cleaned_text'])

    corpus = df['cleaned_text'].fillna('').astype(str).tolist()

    # Vectorise the text to remove highly common and very rare words.
    vectoriser = TfidfVectorizer(stop_words='english', max_df=0.3, min_df=5)
    matrix = vectoriser.fit_transform(corpus)

    #Find word importance by adding up TF-IDF scores across all documents.
    feature_sums = np.asarray(matrix.sum(axis=0)).flatten()
    feature_names = vectoriser.get_feature_names_out()
    
    #Sort words from most important to least important
    sorted_indices = feature_sums.argsort()[::-1]
    sorted_sums = feature_sums[sorted_indices]

    cumulative_sum = np.cumsum(sorted_sums)
    total_sum = cumulative_sum[-1]

    cutoff_index = np.searchsorted(cumulative_sum, total_sum * coverage_ratio)

    #Cutoff the list of words to keep the words within the coverage threshold.
    top_indices = sorted_indices[:cutoff_index + 1]
    top_keywords = feature_names[top_indices]
    top_scores = feature_sums[top_indices]

    sorted_scores = list(zip(top_keywords, top_scores))
    return sorted_scores

def build_user_network(filepath: str, top_keywords: list, user_col: str = 'username') -> nx.Graph:
    """
    Builds the user networks using the sentiment scores, 
    
    Arguments:
        filepath: the path to the CSV file containing the cleaned text and sentiment scores
        top_keywords: the list of top keywords to use for the TF-IDF vectorization, generated by the extract_words function
        user_col: the name of the column containing the user identifiers (default: 'username'), it is 'author_name' for Reddit datasets, and 'username' for Twitter datasets
    Returns:
        A NetworkX graph object representing the user network, with nodes representing users and edges representing similarity based on TF-IDF scores, attributes for sentiment scores and communities.
    """
    #Use top keywords for TF-IDF vectorisation
    vocab = [word for word, score in top_keywords]

    df = pd.read_csv(filepath, usecols=['cleaned_text', user_col, 'sentiment_score'])

    #Limit the number of users to the top 1500 most active users to reduce noise
    top_active_users = df[user_col].value_counts().head(1500).index.tolist()
    df = df[df[user_col].isin(top_active_users)]

    #Group all posts by a user and average the sentiment scores for the user.
    user_data = df.groupby(user_col).agg({
        'cleaned_text': lambda x: ' '.join(x),
        'sentiment_score': 'mean'
    }).reset_index()

    users_array = np.asarray(user_data[user_col])
    sentiments = user_data['sentiment_score'].tolist()

    #Create a dictionary to map sentiment attributes to users
    sentiment_dict = {
        users_array[i]: {'sentiment': sentiments[i]} for i in range(len(users_array))
    }

    tfidf = TfidfVectorizer(vocabulary=vocab, stop_words='english')
    matrix = tfidf.fit_transform(user_data['cleaned_text'])

    similarity_matrix = cosine_similarity(matrix)

    #Testing thresholds to find the optimal threshold for edge creation.
    best_modularity = -1
    best_threshold = 0.0
    best_percentile = 0

    test_percentiles = np.arange(80, 99.5, 0.5)

    for percentile in test_percentiles:
        upper_indices = np.triu_indices_from(similarity_matrix, k=1)
        threshold = np.percentile(similarity_matrix[upper_indices], percentile)

        temp_graph = nx.Graph()

        #Filter out weak semantic connections.
        rows, cols = np.where(similarity_matrix > threshold)
        mask = rows < cols
        r = rows[mask]
        c = cols[mask]

        valid_edges = list(zip(
            users_array[r],
            users_array[c],
            similarity_matrix[r, c]
        ))

        temp_graph.add_weighted_edges_from(valid_edges)
        temp_graph.remove_nodes_from(list(nx.isolates(temp_graph)))

        #Skip testing if the graph is too small, avoiding meaningless communities.
        if len(temp_graph.nodes) < 10:
            continue

        #Leiden algo only use ig_graph, so conversion needed.
        ig_graph = ig.Graph.from_networkx(temp_graph)
        weights = ig_graph.es['weight']

        #Find communities using Leiden algorithm
        partition = leidenalg.find_partition(
            ig_graph,
            leidenalg.ModularityVertexPartition,
            weights=weights,
            seed=42
        )

        #Record the best scores for edge creation
        if len(partition) > 1:
            modularity = partition.quality()
            if modularity > best_modularity:
                best_modularity = modularity
                best_threshold = threshold
                best_percentile = percentile

    #Rebuild the final graph using optimal threshold
    graph = nx.Graph()
    graph.add_nodes_from(users_array)
    nx.set_node_attributes(graph, sentiment_dict)

    rows, cols = np.where(similarity_matrix > best_threshold)
    mask = rows < cols
    r = rows[mask]
    c = cols[mask]

    final_edges = list(zip(
        users_array[r],
        users_array[c],
        similarity_matrix[r, c]
    ))

    graph.add_weighted_edges_from(final_edges)
    isolated = list(nx.isolates(graph))
    graph.remove_nodes_from(isolated)

    #Assign community labels to nodes
    ig_final = ig.Graph.from_networkx(graph)
    final_partition = leidenalg.find_partition(
        ig_final,
        leidenalg.ModularityVertexPartition,
        weights=ig_final.es['weight'],
        seed=42
    )

    community_map = {node: final_partition.membership[i] for i, node in enumerate(graph.nodes())}
    nx.set_node_attributes(graph, community_map, 'community')

    print(f"Best Modularity: {best_modularity:.4f} at Threshold: {best_threshold:.4f} (Percentile: {best_percentile}%)")
    
    #Measures if users connect with similar sentiment 
    assortativity = nx.numeric_assortativity_coefficient(graph, 'sentiment')
    print(f"Assortativity Coefficient: {assortativity:.4f}")
    
    #Identifies the bridge nodes that connect different communities
    centrality = nx.betweenness_centrality(graph, weight='weight')
    nx.set_node_attributes(graph, centrality, 'betweenness_centrality')

    top_bridge_nodes = sorted(centrality.items(), key=lambda x: x[1], reverse=True)[:10]
    print("Top Bridge Nodes (Betweenness Centrality):")
    for node, value in top_bridge_nodes:
        print(f"  {node}: {value:.4f}")
    return graph

def analyse_topics(graph: nx.Graph, df: pd.DataFrame, user_col: str, n_topics: int = 5, min_users: int = 30) -> None:
    """
    Analyse the topics within each community of the user network using LDA topic modeling.

    Arguments:
        graph: the NetworkX graph object representing the user network
        df: the original DataFrame containing the cleaned text and user column.
        user_col: the name of the column containing the user identifiers
        n_topics: the number of topics to extract using LDA
        min_users: the minimum number of users required to perform LDA, to filter out really small inconsequential communities.
    Returns:
        None, but the function will print the top keywords for each community based on LDA topic modeling.
    """
    
    #Extract communities generated from Leiden
    node_data = [{'username': node, 'community': data['community']}
                 for node, data in graph.nodes(data=True)]
    community_df = pd.DataFrame(node_data)

    #Re-merge the users with original raw text data
    merged_df = pd.merge(community_df, df[[user_col, 'cleaned_text']], left_on='username', right_on=user_col)

    #Iterate through echo chamber and perform LDA
    for chamber in sorted(merged_df['community'].unique()):
        text_data = merged_df[merged_df['community'] == chamber]['cleaned_text']

        if len(text_data) < min_users:
            continue

        vectoriser = TfidfVectorizer(stop_words='english', max_features=500)
        matrix = vectoriser.fit_transform(text_data)

        lda = LatentDirichletAllocation(n_components=n_topics, random_state=42)
        lda.fit(matrix)

        words = vectoriser.get_feature_names_out()
        print(f"\nCommunity {chamber} - Top Topics:")
        for topic_index, topic in enumerate(lda.components_):
            top_words = [words[i] for i in topic.argsort()[-10:]]
            print(f"  Topic {topic_index + 1}: {', '.join(top_words)}")

def plot_network(graph, title: str, ax):
    pos = nx.spring_layout(graph, k=0.15, iterations=50, seed=42)
    sentiments = [graph.nodes[node].get('sentiment', 0.0) for node in graph.nodes()]

    ax.set_facecolor('white')

    nx.draw_networkx_edges(
        graph, pos,
        alpha=0.6,       
        width=0.2,        
        edge_color="black",
        ax=ax
    )

    nodes = nx.draw_networkx_nodes(
        graph, pos,
        node_size=30,
        node_color=sentiments,
        cmap=plt.cm.coolwarm_r,
        vmin=-1.0, 
        vmax=1.0,
        alpha=0.8,
        edgecolors='black',
        linewidths=0.3,
        ax=ax
    )

    cbar = plt.colorbar(nodes, shrink=0.5, pad=0.05, ax=ax)
    cbar.set_label('VADER Sentiment Score (-1 Negative to +1 Positive)', color='black', size=12)
    cbar.ax.yaxis.set_tick_params(color='black')
    plt.setp(plt.getp(cbar.ax.axes, 'yticklabels'), color='black')

    ax.set_title(title, fontsize=14, color='black')
    ax.axis('off')

#datasets that are significant enough to be plotted
datasets_to_run = [
    {
        "filepath": "dataset/twitter_Iran_Strikes_BASELINE_VADER.csv",
        "title": "Twitter Iran Strikes - Baseline",
        "user_col": "username",
        "coverage_ratio": 0.7
    },
    {
        "filepath": "dataset/twitter_Iran_Strikes_EVENT_VADER.csv",
        "title": "Twitter Iran Strikes - Event",
        "user_col": "username",
        "coverage_ratio": 0.7
    },
    {
        "filepath": "dataset/reddit_Iran_Strikes_BASELINE_VADER.csv",
        "title": "Reddit Iran Strikes - Baseline",
        "user_col": "author_name",
        "coverage_ratio": 0.2
    },
    {
        "filepath": "dataset/reddit_Iran_Strikes_EVENT_VADER.csv",
        "title": "Reddit Iran Strikes - Event",
        "user_col": "author_name",
        "coverage_ratio": 0.2
    },
    {
        "filepath": "dataset/twitter_October_7_BASELINE_VADER.csv",
        "title": "Twitter October 7 - Baseline",
        "user_col": "username",
        "coverage_ratio": 0.7
    },
    {
        "filepath": "dataset/twitter_October_7_EVENT_VADER.csv",
        "title": "Twitter October 7 - Event",
        "user_col": "username",
        "coverage_ratio": 0.7
    },
    {
        "filepath": "dataset/reddit_October_7_BASELINE_VADER.csv",
        "title": "Reddit October 7 - Baseline",
        "user_col": "author_name",
        "coverage_ratio": 0.2
    },
    {
        "filepath": "dataset/reddit_October_7_EVENT_VADER.csv",
        "title": "Reddit October 7 - Event",
        "user_col": "author_name",
        "coverage_ratio": 0.2
    },
    {
        "filepath": "dataset/twitter_ICC_Arrest_BASELINE_VADER.csv",
        "title": "Twitter ICC Arrest - Baseline",
        "user_col": "username",
        "coverage_ratio": 0.7
    },
    {
        "filepath": "dataset/twitter_ICC_Arrest_EVENT_VADER.csv",
        "title": "Twitter ICC Arrest - Event",
        "user_col": "username",
        "coverage_ratio": 0.7
    },
    {
        "filepath": "dataset/reddit_ICC_Arrest_BASELINE_VADER.csv",
        "title": "Reddit ICC Arrest - Baseline",
        "user_col": "author_name",
        "coverage_ratio": 0.2
    },
    {
        "filepath": "dataset/reddit_ICC_Arrest_EVENT_VADER.csv",
        "title": "Reddit ICC Arrest - Event",
        "user_col": "author_name",
        "coverage_ratio": 0.2
    }
]

#loop to plot all the datasets in groups of 4 
for i in range(0, len(datasets_to_run), 4):
    
    event_group = datasets_to_run[i:i+4]
    base_name = event_group[0]['title'].replace("Twitter ", "").split("-")[0].strip().replace(" ", "_")
    
    fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(20, 20))
    fig.patch.set_facecolor('white')
    
    axes = axes.flatten()

    for j, data in enumerate(event_group):
        
        top_words = extract_words(data['filepath'], data['coverage_ratio'])
        graph = build_user_network(data['filepath'], top_words, user_col=data['user_col'])
        
        analyse_topics(graph, pd.read_csv(data['filepath']), user_col=data['user_col'], n_topics=5)
        
        plot_network(graph, data['title'], axes[j])

    plt.tight_layout()
    output_filename = f"dataset/{base_name}_Master_Comparison.png"
    plt.savefig(output_filename, dpi=300, facecolor='white', bbox_inches='tight')
    
    plt.close(fig)
